# Modifications © 2019 Hashmap, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runners:
#  - name: websocket_1
#    variety: socket
#    type: consumer
#    uri: wss://ws.coincap.io/trades/binance
#    stage:
#      type: local
#      path: 'tmp'
#    batch_configuration:
#      size: 10

  - name: websocket_2
    variety: socket
    type: consumer
    uri: wss://ws.coincap.io/trades/huobi
    stage:
      type: s3
      access_key:
      secret_key:
      bucket:
    batch_configuration:
      size: 10

#  - name: websocket_3
#    variety: socket
#    type: consumer
#    uri: wss://ws.coincap.io/trades/hitbtc
#    stage:
#      type: local
#      path: 'tmp'
#    batch_configuration:
#      size: 10000


  #- name: postgres
  #  variety: postgres
  #  depends_on:
  #    - websocket_1
  #    - websocket_2
  #    - websocket_3
  #  type: producer
  #  profile: postgres
